# Usa una imagen base con R y Shiny preinstalados
FROM rocker/shiny-verse:latest

# Instala paquetes adicionales necesarios
RUN R -e "install.packages(c('shinydashboard', 'DT'))"

# Copia tu aplicación al directorio del servidor Shiny
COPY . /srv/shiny-server/

# Expone el puerto en el que Shiny Server escucha
EXPOSE 3838

# Inicia el servidor Shiny
CMD ["/usr/bin/shiny-server"]
